### ISSUE TITLE
Course-3 - TypeError: ChannelClosed.__init__() missing 1 required positional argument: 'reply_text'

### ISSUE THREAD

**Issue by air71818** [decodingml/llm-twin-course#29]
When I cd into `llm-twin-course/3-feature-pipeline` and run 
```
RUST_BACKTRACE=full python3.11 -m bytewax.run main.py  
```
or
```
RUST_BACKTRACE=full python3.11 -m bytewax.run main:flow
```

I got
```
thread '<unnamed>' panicked at src/inputs.rs:441:37:
Box<dyn Any>
stack backtrace:
   0:        0x104fb7090 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0524bd1b527203b8
   1:        0x104fd7ed8 - core::fmt::write::h74be1333b0a6ddea
   2:        0x104fb4070 - std::io::Write::write_fmt::h6c011b665b2d7d4b
   3:        0x104fb6ed0 - std::sys_common::backtrace::print::he25ff7dac6402434
   4:        0x104fb88bc - std::panicking::default_hook::{{closure}}::h41763ba018b93bf7
   5:        0x104fb85d4 - std::panicking::default_hook::h017c44660373840e
   6:        0x104fb8e00 - std::panicking::rust_panic_with_hook::h221a0baf52ecd48a
   7:        0x10493db0c - std::panicking::begin_panic::{{closure}}::h3cb625e84d2fa59b
   8:        0x10493d734 - std::sys_common::backtrace::__rust_end_short_backtrace::h9b5b04fbd92357bf
   9:        0x104fe2a2c - std::panicking::begin_panic::h10ac1f508579215d
  10:        0x10481d770 - bytewax::inputs::FixedPartitionedSource::partitioned_input::{{closure}}::{{closure}}::{{closure}}::h4fc8b32076461a92
  11:        0x1048047bc - tracing::span::Span::in_scope::h37c7b0e329a3cea8
  12:        0x1046a5538 - <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule::hf3b252a2e8257f48
  13:        0x1049cc748 - <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule::hc96337c3aa34cbfc
  14:        0x104e405f8 - timely::worker::Wrapper::step::h49f4bc0b82946908
  15:        0x1049dfeb8 - timely::worker::Worker<A>::step_or_park::hb6654377a23c113e
  16:        0x104806c9c - tracing::span::Span::in_scope::h6059469a16cfd41a
  17:        0x1049c9130 - bytewax::worker::Worker<A,F>::run::ha69d06e4890174b1
  18:        0x104801f1c - tracing::span::Span::in_scope::h2384075560b698a3
  19:        0x1049a7eec - timely::execute::execute_directly::hf82ed75b777fcf5c
  20:        0x10495d8f0 - bytewax::run::run_main::h88816a2758f2257b
  21:        0x1049601a8 - bytewax::run::cli_main::h085ee14d260289f8
  22:        0x104960efc - bytewax::run::_::__pyfunction_cli_main::h1dba787f712c55eb
  23:        0x10494b4dc - pyo3::impl_::trampoline::trampoline::h3d82501b9b709bd2
  24:        0x104960b64 - bytewax::run::_::<impl bytewax::run::cli_main::MakeDef>::DEF::trampoline::h3fe61f5cb448d702
  25:        0x102dbdbb0 - _cfunction_vectorcall_FASTCALL_KEYWORDS
  26:        0x102d72e34 - __PyVectorcall_Call
  27:        0x102e521f0 - __PyEval_EvalFrameDefault
  28:        0x102e45254 - _PyEval_EvalCode
  29:        0x102e416fc - _builtin_exec
  30:        0x102dbdbb0 - _cfunction_vectorcall_FASTCALL_KEYWORDS
  31:        0x102e50288 - __PyEval_EvalFrameDefault
  32:        0x102e54a60 - __PyEval_Vector
  33:        0x102eb7124 - _pymain_run_module
  34:        0x102eb6c80 - _Py_RunMain
  35:        0x102eb7de0 - _Py_BytesMain

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/lib/python3.11/site-packages/bytewax/run.py", line 354, in <module>
    cli_main(**kwargs)
TypeError: ChannelClosed.__init__() missing 1 required positional argument: 'reply_text'
```

I could not reproduced the result or launch my bytewax, and I do not survey some useful information...

**Comment by iusztinpaul** [comment]
Hello,

This issue has been fixed with the latest changes.
