### ISSUE TITLE
Getting issue with docker logs

### ISSUE THREAD

**Issue by solvusAI** [decodingml/llm-twin-course#34]
{"statusCode": 200, "body": "Link processed successfully"}%                                                                                                                                                 (llm-twin) goutamgupta@goutamguptas-MacBook-Pro llm-twin-course % docker logs llm-twin-bytewax
2024-08-07 10:04:59 [info     ] Couldn't access the collection. Creating a new one... cls=data_flow.stream_output collection_name=cleaned_posts
2024-08-07 10:04:59 [info     ] Couldn't access the collection. Creating a new one... cls=data_flow.stream_output collection_name=cleaned_articles
2024-08-07 10:04:59 [info     ] Couldn't access the collection. Creating a new one... cls=data_flow.stream_output collection_name=cleaned_repositories
2024-08-07 10:04:59 [info     ] Couldn't access the collection. Creating a new one... cls=data_flow.stream_output collection_name=vector_posts
2024-08-07 10:04:59 [info     ] Couldn't access the collection. Creating a new one... cls=data_flow.stream_output collection_name=vector_articles
2024-08-07 10:04:59 [info     ] Couldn't access the collection. Creating a new one... cls=data_flow.stream_output collection_name=vector_repositories
2024-08-07 10:04:59 [error    ] Error while fetching message from queue. cls=data_flow.stream_input queue_name=default
2024-08-07 10:05:09 [error    ] Error while fetching message from queue. cls=data_flow.stream_input queue_name=default
2024-08-07 10:05:19 [info     ] Received message.              cls=data_logic.dispatchers data_type=users
thread '<unnamed>' panicked at src/operators/mod.rs:169:33:
Box<dyn Any>
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/bytewax/run.py", line 354, in <module>
    cli_main(**kwargs)
ValueError: (src/operators/mod.rs:177:80) error calling `mapper` in step "Streaming ingestion pipeline.raw dispatch.flat_map_batch"
Caused by => ValueError: (src/operators/mod.rs:86:28) error while iterating through batch
Caused by => ValueError: Unsupported data type
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/bytewax/operators/__init__.py", line 1199, in <genexpr>
    return (mapper(x) for x in xs)
            ^^^^^^^^^
  File "/usr/src/app/data_logic/dispatchers.py", line 41, in handle_mq_message
    raise ValueError("Unsupported data type")

Process ended.
Keeping container alive...

**Comment by zhangruotian** [comment]
> {"statusCode": 200, "body": "Link processed successfully"}% (llm-twin) goutamgupta@goutamguptas-MacBook-Pro llm-twin-course % docker logs llm-twin-bytewax 2024-08-07 10:04:59 [info ] Couldn't access the collection. Creating a new one... cls=data_flow.stream_output collection_name=cleaned_posts 2024-08-07 10:04:59 [info ] Couldn't access the collection. Creating a new one... cls=data_flow.stream_output collection_name=cleaned_articles 2024-08-07 10:04:59 [info ] Couldn't access the collection. Creating a new one... cls=data_flow.stream_output collection_name=cleaned_repositories 2024-08-07 10:04:59 [info ] Couldn't access the collection. Creating a new one... cls=data_flow.stream_output collection_name=vector_posts 2024-08-07 10:04:59 [info ] Couldn't access the collection. Creating a new one... cls=data_flow.stream_output collection_name=vector_articles 2024-08-07 10:04:59 [info ] Couldn't access the collection. Creating a new one... cls=data_flow.stream_output collection_name=vector_repositories 2024-08-07 10:04:59 [error ] Error while fetching message from queue. cls=data_flow.stream_input queue_name=default 2024-08-07 10:05:09 [error ] Error while fetching message from queue. cls=data_flow.stream_input queue_name=default 2024-08-07 10:05:19 [info ] Received message. cls=data_logic.dispatchers data_type=users thread '' panicked at src/operators/mod.rs:169:33: Box note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> Traceback (most recent call last): File "", line 198, in _run_module_as_main File "", line 88, in _run_code File "/usr/local/lib/python3.11/site-packages/bytewax/run.py", line 354, in cli_main(**kwargs) ValueError: (src/operators/mod.rs:177:80) error calling `mapper` in step "Streaming ingestion pipeline.raw dispatch.flat_map_batch" Caused by => ValueError: (src/operators/mod.rs:86:28) error while iterating through batch Caused by => ValueError: Unsupported data type Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/bytewax/operators/**init**.py", line 1199, in return (mapper(x) for x in xs) ^^^^^^^^^ File "/usr/src/app/data_logic/dispatchers.py", line 41, in handle_mq_message raise ValueError("Unsupported data type")
> 
> Process ended. Keeping container alive...

Same here. Have you found a workaround? @solvusAI

**Comment by solvusAI** [comment]
@zhangruotian no fix found yet.

**Comment by iusztinpaul** [comment]
Hello,

I fixed this issue.

If you want to progress, pull the latest code, rebuild the Docker image, and it should work.
