### ISSUE TITLE
TypeError: No constructor defined

### ISSUE THREAD

**Issue by Galleons2029** [decodingml/llm-twin-course#39]
I am encountering a TypeError: No constructor defined error when using the flat_map_batch operator in Bytewax. The error occurs during the execution of my data flow pipeline, which uses a series of custom dispatchers for data processing. The error message provided by the runtime is as follows:
```
TypeError: (src/operators.rs:206:80) error calling `mapper` in step "Stream Ingestion Pipeline.Raw Dispatcher.flat_map_batch"
Caused by => TypeError: No constructor defined
```
### Error Details
Below is the full stack trace of the error:
```
comet_ml is installed but `COMET_API_KEY` is not set.
2024-09-17 17:18:20 [info     ] Received message.              cls=app.feature_pipeline.data_logic.dispatchers data_type=posts
thread '<unnamed>' panicked at src/operators.rs:198:33:
Box<dyn Any>
stack backtrace:
   0:     0x7ab1e936cb7c - std::backtrace_rs::backtrace::libunwind::trace::ha69d38c49f1bf263
   ...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/weyon2/miniconda3/envs/job_recom/lib/python3.11/site-packages/bytewax/run.py", line 355, in <module>
    cli_main(**kwargs)
TypeError: (src/operators.rs:206:80) error calling `mapper` in step "Stream Ingestion Pipeline.Raw Dispatcher.flat_map_batch"
Caused by => TypeError: No constructor defined
```

**Comment by iusztinpaul** [comment]
Hello,

We remastered the course and fixed all these issues in the last commit
